#!/bin/bash 
function cdo() {
echo '1. SP .../obj-7k-sup3-sp-earl7'
echo '2. RP .../obj-7k-sup3-rp-earl7'
echo '3. RSP.../obj-m8500-sup3-sp-earl7'
echo '4. RSP.../obj-m8500-sup3-rp-earl7'
echo '5. x40g../obj-m8500-x40g'
read OPT_C;
VIEW_NAME=`echo $CLEARCASE_CMDLINE | cut -d' ' -f2`

if [ $OPT_C = "1" ]
then
files=("/nobackup/sbhal/build_"$VIEW_NAME"/vob/ios/sys/obj-7k-sup3-sp-earl7");
echo "${files[@]}";
elif [ $OPT_C = "2" ]
then
files=("/nobackup/sbhal/build_"$VIEW_NAME"/vob/ios/sys/obj-7k-sup3-rp-earl7");
cd "${files[@]}";
elif [ $OPT_C = "3" ]
then
files=("/nobackup/sbhal/build_"$VIEW_NAME"/vob/ios/sys/obj-m8500-sup3-sp-earl7");
cd "${files[@]}";
elif [ $OPT_C = "4" ]
then
files=("/nobackup/sbhal/build_"$VIEW_NAME"/vob/ios/sys/obj-m8500-sup3-rp-earl7");
cd "${files[@]}";
elif [ $OPT_C = "5" ]
then
files=("/nobackup/sbhal/build_"$VIEW_NAME"/vob/ios/sys/obj-m8500-x40g");
cd "${files[@]}";
elif [ $OPT_C = "0" ]
then
exit 0
fi
}

